# Generated by Django 4.2 on 2023-04-20 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_category_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
